# Generated by Django 6.0.4 on 2026-04-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='idempotencykey',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='payout',
            name='retry_count',
        ),
        migrations.AddField(
            model_name='merchant',
            name='balance',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount_paise',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='LedgerEntry',
        ),
    ]
