# Generated by Django 6.0.4 on 2026-04-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_idempotencykey_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='amount_paise',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='idempotency_key',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='IdempotencyKey',
        ),
    ]
