# Generated by Django 6.0.4 on 2026-04-26 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_merchant_balance_payout_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idempotencykey',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='idempotencykey',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='idempotencykey',
            name='response',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='idempotency_key',
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.payout'),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=10),
        ),
    ]
